### PR TITLE
Feat/urban1d

### PR DESCRIPTION
**Pull request by philcrawford**
Initial support for Urban 1D INP files. 

Provides read/write functionality for the following subsections:
- Options 
- JUNCTIONS
- RAINGAUGES

### CODE REVIEW

**Comment by joe-pierce** [comment]
@philcrawford I've noticed that there isn't any validation againts the 'options' dictionary, have you thought about adding this? Secondly, you mention in the code that option order is preserved, can you elaborate on how this is achieved? As far as I can tell it is just stored in a dictionary so isn't preserving order?

**Comment by joe-pierce** [comment]
@philcrawford I think we should include validation for unit 'name' attributes. Currently you can change the name of a junction to something really long, and then only the first 15 characters are retained in the output when saved.

**Comment by joe-pierce** [comment]
@philcrawford could you have a look at any parts of the code i've commented `# TODO: JP Review` and resolve any actions.

**Comment by philcrawford** [comment]
> you mention in the code that option order is preserved, can you elaborate on how this is achieved? As far as I can tell it is just stored in a dictionary so isn't preserving order?

As discussed.  Python 3.7 now preserves dictionary order.  No further action required

**Comment by philcrawford** [comment]
> # TODO: JP Review

Actions addressed and committed.

**Comment by philcrawford** [comment]
> @philcrawford I've noticed that there isn't any validation againts the 'options' dictionary, have you thought about adding this? 

Validation on options added.

**Pull request merged**
