### PR TITLE
31 implement automated backup for files

### PR DESCRIPTION
**Pull request by matthewjwhittle-jacobs**
#31

### CODE REVIEW

**Comment by joe-pierce** [comment]
This looks really good @matthewjwhittle-jacobs. Tests have passed for me, and the functionality works as expected. 
Only comment from me on the code is there's a bit of mixed use of os.path, glob and pathlib - generally i'd suggest using pathlib for all of this stuff as it has superseded os.path and has it's own glob implementation.

I think there's room to extend the functionality of the backup stuff, for example being able to restore directly to an instance of a class (so you can quickly test equivalence) and provide an interface to the backups csv - but I think they can come later anyway. 

Happy to merge and close this issue.

**Comment by joe-pierce** [comment]
I've noticed one bug in the tests that will need fixing - the [tearDown method for TestFile](https://github.com/People-Places-Solutions/floodmodeller-api/blob/2838a0cf10befd658963c22cafe85e6c3e6cfb2c/test/test_all_classes.py#L283) actually wipes the main backup folder rather than the test one. I think this is because the test backup folder is only used for the TestBackUp test case.

Can you resolve this to also use the test backup folder please.

**Comment by matthewjwhittle-jacobs** [comment]
I've fixed the bug. 

However, this has raised another issue. If as a user I want to set a non-standard backup location, I should be able to do that once and have it persist between sessions. At the moment you can only do that when creating an instance of the backup class and it won't be actually used when a file is loaded and backed up (since this uses the default value for the parameter).

I should be able to do something like this and then it be used whenever I load a file:
```python
from backup import BackupControl
backup_control = BackupControl()
backup_control.set_default_backup_dirname("my_custom_fm_backups") 

# Makes a backup in the custom location:
from floodmodeller_api import DAT
my_dat = DAT("my-file.DAT")
```

What is the best approach for implementing this? config file somewhere?

**Comment by joe-pierce** [comment]
Yea I think a config json file would work, and allow a user to either change the default backup directory manually, or can change programatically with something like:
```python
import floodmodeller_api
floodmodeller_api.config.default_backup_dir = "my_custom_fm_backups"
```
And have this persist between sessions in the config file. **But saying all that, I think for now let's just keep it so that there's the one location for backups and we can add this extra thing as an issue to look at later**

**Comment by matthewjwhittle-jacobs** [comment]
I've removed the custom backup method. The tests now just run on the default backup directory. Obviously, if you're using the API alongside developing this could be problematic. I'll add a separate issue to record some of the other changes we've discussed (method to query backup logs and custom backup locations). 

Are you happy for me to merge?

**Comment by matthewjwhittle-jacobs** [comment]
I've removed the custom backups and added a method to remove backups only for a particular file. That way we can run the tests, and clear backups to ensure everything works and the scope is only limited to the testing file. Have added some tests for this too. 

I think we're done on this one for now so please merge if you're happy @joe-pierce 

I'll add another issue for features we would ultimately like:
- Clearer method for querying backup data and retrieving a backup (date range, file type, file id, etc)
- Method to define a custom location that persists between sessions and across projects

**Comment by joe-pierce** [comment]
I've made a small change to add index=False when clearing a backup, because when it is read in with pandas and then back out to csv it is adding a dummy index each time. So after running the tests a few times in a row the backup csv gets messed up. I have also ran it through black just for consistent formatting. Other than that ready to merge.

**Pull request merged**
