### PR TITLE
15 improved test module

### PR DESCRIPTION
**Pull request by matthewjwhittle-jacobs**
#15

### CODE REVIEW

**Comment by matthewjwhittle-jacobs** [comment]
Looks like the automatic unit tests before merge thing is working 🥳

**Comment by joe-pierce** [comment]
This is looking good thank you - I've made a couple changes in the main code where I identified some new issues.

**Comment by joe-pierce** [comment]
Before I merge this could you also add in the backup tests you'd added in the previous unit test stuff

**Comment by matthewjwhittle-jacobs** [comment]
@joe-pierce Thanks for making those changes. I've added the backup tests and this should be ok to merge now.

**Pull request merged**
