### PR TITLE
Tuflow conversion

### PR DESCRIPTION
**Pull request by scleakey**
- Merged #51
- Moved toolbox into main code folder
- Created tuflow conversion as an example tool
- Fixed some minor typos

### CODE REVIEW

**Comment by joe-pierce** [comment]
@scleakey I've made some changes to how the toolbox side of things work. You should be able to run `python setup.py develop` to add the script entry points to your path so that you can run the tools more cleanly. 

One thing to add in for the first version would be to include the logic for different types of computational area - it looks like you have most of the code there already, but just a case of including it. 

Another smaller thing would be to handle cases in the topography conversion where no layers exist - currently this logs an error, when in fact there just aren't any relevant lines in the tgc.

**Comment by scleakey** [comment]
@joe-pierce I had a thought about renaming that folder from helpers to tuflow_to_flood_modeller ... the functionality in it might be usable for other types of model conversion besides TUFLOW. But I guess we could rename it to something else if that should happen?

**Comment by joe-pierce** [comment]
Let's leave it as is for now - but if we want to share across other conversion tools in the future we can rename/refactor at that point 👍

**Comment by scleakey** [comment]
@joe-pierce

Requested changes here: https://github.com/People-Places-Solutions/floodmodeller-api/blob/dd7395964481b3ce942f95aff9666ce394faa433/floodmodeller_api/toolbox/model_conversion/tuflow_to_floodmodeller/model_converter.py#L154-L193

I have also added some tests for model_converter.py (there were none previously), and cleaned up the 1D initialisation so there aren't a bunch of if statements everywhere

**Comment by BRgit7** [comment]
I'm still looking to:
- Add culverts - which may allow channels to not be split up so much in flood modeller
- How to set a flag for channels vs culverts
- Make subclasses for FMFileWrapper (DATWrapper, IEFWrapper, etc.)
- Turn the script class into a proper class
- Add that class to component_coverter

**Pull request merged**
