### PR TITLE
Add support for 2D xml model files

### PR DESCRIPTION
**Pull request by joe-pierce**
First iteration complete of the XML2D class, which allows for reading/editing Flood Modeller 2d model files (.xml).

This code includes:
- XML2D class: imported and used very similarly to all other classes with key methods
- Validation of xml files against xml schema
- Test cases included in test module
- Documentation updates for XML2D class

### CODE REVIEW

**Review by scleakey — COMMENTED** [review]
I have some questions/comments:
- I had to install `lxml` - is this done automatically when you install `floodmodeller-api`?
- Should `self.data` be `self._data`?
- The documentation says that attributes not present will return `None` but, when I tried it out, they cause an `AttributeError`

**Comment by philcrawford** [comment]
I agree with @scleakey comments above. Thoughts:  
- **lxml dependency** - is it worth listing somewhere what the list of dependencies is?  This could either be at the api level, or potentially at the class level (e.g. IEF, INP, XML2D).  
- **'None' attributes** - suggest we will need to pre-populate the full set of potential attributes at initialisation similar to INP class (and others) else it limits the editing possibilities

**Comment by philcrawford** [comment]
Other comments:
- Help documentation is clear and well written.  Pleased to see it showing an example of how to access domain attributes e.g. domain_id
- **GIS data** - GIS data file paths are interpreted and saved within the FM-API attributes with double \\ e.g. 'GIS\\5M_DTM.asc' - do we want to show it like this?

**Comment by joe-pierce** [comment]
I've added lxml as a package dependency, changed `.data` to `._data` and set the missing attributes to None values.

For the file paths @philcrawford, it still stores the string with one backslash, it's just how python represents backslashes in strings as they are escape characters. In terms of validation, to keep things simple I think we should leave this as all validation is done against the xml schema.

**Comment by joe-pierce** [comment]
@scleakey @philcrawford any more comments before merge?

**Comment by scleakey** [comment]
no more comments - looks good

**Pull request merged**
